name: Ruby Build

on:
  push:
    branches: [ master ]  # main 또는 master
  pull_request:
    branches: [ master ]  # main 또는 master 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install